"""empty message

Revision ID: 104ba77cf640
Revises: a82599a7a928
Create Date: 2026-03-17 17:07:31.724905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '104ba77cf640'
down_revision = 'a82599a7a928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality', schema=None) as batch_op:
        batch_op.alter_column('point_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality', schema=None) as batch_op:
        batch_op.alter_column('point_id',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
