"""empty message

Revision ID: 94371c8439fa
Revises: b7e2a1c0d4f8
Create Date: 2026-03-21 14:33:56.820548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94371c8439fa'
down_revision = 'b7e2a1c0d4f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_point_id', ['point_id', 'date_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_quality_point_id'), ['point_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_quality_point_id'), type_='unique')
        batch_op.drop_constraint('unique_point_id', type_='unique')

    # ### end Alembic commands ###
