"""empty message

Revision ID: a82599a7a928
Revises: fc33b29a0e96
Create Date: 2026-03-17 16:22:50.391083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a82599a7a928'
down_revision = 'fc33b29a0e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('date', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_date_quality_id_quality'), type_='foreignkey')
        batch_op.drop_column('quality_id')

    with op.batch_alter_table('quality', schema=None) as batch_op:
        batch_op.add_column(sa.Column('point_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_quality_date_id_date'), 'date', ['date_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_quality_date_id_date'), type_='foreignkey')
        batch_op.drop_column('date_id')
        batch_op.drop_column('point_id')

    with op.batch_alter_table('date', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quality_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_date_quality_id_quality'), 'quality', ['quality_id'], ['id'])

    # ### end Alembic commands ###
