"""empty message

Revision ID: bed9c394d967
Revises: 94371c8439fa
Create Date: 2026-03-21 15:15:39.965239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed9c394d967'
down_revision = '94371c8439fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_code'))
    )
    with op.batch_alter_table('quality', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_quality_point_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_quality_point_id'), ['point_id'], unique=True)

    op.drop_table('email_code')
    # ### end Alembic commands ###
