"""empty message

Revision ID: fc33b29a0e96
Revises: 
Create Date: 2026-03-16 22:50:29.695152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc33b29a0e96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FCR', sa.Float(), nullable=True),
    sa.Column('ECR', sa.Float(), nullable=True),
    sa.Column('PH', sa.Float(), nullable=True),
    sa.Column('ORP', sa.Float(), nullable=True),
    sa.Column('NTU', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality'))
    )
    op.create_table('date',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('quality_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quality_id'], ['quality.id'], name=op.f('fk_date_quality_id_quality')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_date'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('date')
    op.drop_table('quality')
    # ### end Alembic commands ###
